version: '3'

vars:
  APP_SERVICES_CMD: 'gcloud app services'

tasks:

  default:
    cmds:
      - echo '{{.APP_SERVICES_CMD}} ...'

  describe:
    requires:
      vars: [GCP_PROJECT, GAE_SERVICE]
    vars:
      _FORMAT: '{{.FORMAT | default "json"}}'
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - >-
        {{.APP_SERVICES_CMD}} describe
        {{.GAE_SERVICE}}
        --format={{._FORMAT}}
        --project={{.GCP_PROJECT}}
