version: '3'

vars:
  GCLOUD_CMD: 'gcloud builds'

tasks:

  default:
    cmds:
      - cmd: echo '{{.GCLOUD_CMD}} ...'

  submit_using_pack:
    requires:
      vars: [GCP_PROJECT, IMAGE_TAG]
    dir: '{{.USER_WORKING_DIR}}'
    vars:
      BUILD_DIR: '{{.USER_WORKING_DIR}}'
    cmds:
      - >-
        {{.GCLOUD_CMD}} submit {{.BUILD_DIR}}
        --pack='image={{.IMAGE_TAG}}'
        --dir={{.BUILD_DIR}}
        --project={{.GCP_PROJECT}}

  submit_using_tag:
    requires:
      vars: [GCP_PROJECT, IMAGE_TAG]
    dir: '{{.USER_WORKING_DIR}}'
    vars:
      BUILD_DIR: '{{.USER_WORKING_DIR}}'
    cmds:
      - >-
        {{.GCLOUD_CMD}} submit {{.BUILD_DIR}}
        --tag={{.IMAGE_TAG}}
        --dir={{.BUILD_DIR}}
        --project={{.GCP_PROJECT}}