version: '3'

includes:
  gcloud_builds_triggers:
    taskfile: 'builds_triggers.yaml'
    aliases: [triggers]

vars:
  BUILDS_CMD: 'gcloud builds'

tasks:

  default:
    cmds:
      - cmd: echo '{{.BUILDS_CMD}} ...'

  submit_using_pack:
    requires:
      vars: [GCP_PROJECT, IMAGE_TAG]
    dir: '{{.USER_WORKING_DIR}}'
    vars:
      BUILD_DIR: '{{.USER_WORKING_DIR}}'
    cmds:
      - >-
        {{.BUILDS_CMD}} submit
        {{.BUILD_DIR}}
        --pack='image={{.IMAGE_TAG}}'
        --dir={{.BUILD_DIR}}
        --project={{.GCP_PROJECT}}

  submit_using_tag:
    requires:
      vars: [GCP_PROJECT, IMAGE_TAG]
    dir: '{{.USER_WORKING_DIR}}'
    vars:
      BUILD_DIR: '{{.USER_WORKING_DIR}}'
    cmds:
      - >-
        {{.BUILDS_CMD}} submit 
        {{.BUILD_DIR}}
        --tag={{.IMAGE_TAG}}
        --dir={{.BUILD_DIR}}
        --project={{.GCP_PROJECT}}
