version: '3'

vars:
  GCLOUD_CMD: 'gcloud config'

tasks:

  default:
    cmds:
      - echo '{{.GCLOUD_CMD}} ...'

  set_project:
    requires:
      vars: [GCP_PROJECT]
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - cmd: '{{.GCLOUD_CMD}} set project {{.GCP_PROJECT}}'
