version: '3'

includes:
  https:
    taskfile: "../common/https.yaml"
  gcloud_identity_providers:
    taskfile: "identity_providers.yaml"
    aliases: [providers]

vars:
  IDENTITY_GAPI: 'identitytoolkit.googleapis.com/admin/v2'

tasks:

  default:
    cmds:
      - cmd: echo '{{.IDENTITY_GAPI}} ...'

  get_config:
    requires:
      vars:
        - GCP_PROJECT
        - OUTPUT
    dir: '{{.USER_WORKING_DIR}}'
    vars:
      PARENT: 'projects/{{.GCP_PROJECT}}'
      FIELDS: '{{.FIELDS | default "*"}}'
    cmds:
      - task: https:exec_get
        vars:
          BEARER: 'google:access_token'
          ENDPOINT: '{{.IDENTITY_GAPI}}/{{.PARENT}}/config'
          QUERY: >-
            fields=={{.FIELDS}}
          HEADERS: >-
            content-type:'application/json'
            accept:'application/json'
            x-goog-user-project:{{.GCP_PROJECT}}
          OUTPUT: '{{.OUTPUT}}'
      - cat -n {{.OUTPUT}}

  update_config:
    requires:
      vars:
        - GCP_PROJECT
        - MASK
        - CONFIG
    dir: '{{.USER_WORKING_DIR}}'
    vars:
      PARENT: 'projects/{{.GCP_PROJECT}}'
    cmds:
      - task: https:exec_patch
        vars:
          BEARER: 'google:access_token'
          ENDPOINT: '{{.IDENTITY_GAPI}}/{{.PARENT}}/config'
          QUERY: >-
            updateMask=={{.MASK}}
            fields=={{.MASK}}
          HEADERS: >-
            content-type:'application/json'
            accept:'application/json'
            x-goog-user-project:{{.GCP_PROJECT}}
          BODY: '{{.CONFIG}}'
