version: '3'

includes:
  gcloud_run_services:
    taskfile: "run_services.yaml"
    aliases: [run_services]

vars:
  RUN_CMD: 'gcloud run'

tasks:

  default:
    cmds:
      - echo '{{.RUN_CMD}} ...'

  deploy:
    aliases:
      - update_service
      - deploy_container_image
    requires:
      vars: [GCP_PROJECT, RUN_SERVICE, RUN_REGION]
    vars:
      _CMD: >-
        {{if eq .TASK "update_service"}}
        {{.RUN_CMD}} services update
        {{else}}{{.RUN_CMD}}{{end}}
      _CONCURRENCY: '{{.CONCURRENCY | default "1"}}'
      _MIN_INSTANCES: '{{.MIN_INSTANCES | default "0"}}'
      _MAX_INSTANCES: '{{.MAX_INSTANCES | default "1"}}'
      _TIMEOUT: '{{.TIMEOUT | default "1m"}}'
      _CPU: '{{.CPU | default "1"}}'
      _MEMORY: '{{.MEMORY | default "512Mi"}}'
      _GENERATION: '{{.GENERATION | default "1"}}'
      _INGRESS: '{{.INGRESS | default "all"}}'
      _PLATFORM: '{{.PLATFORM | default "managed"}}'
      _CPU_BOOST: '{{.CPU_BOOST | default "no"}}'
      _CPU_THROTTLE: '{{.CPU_THROTTLE | default "yes"}}'
      _SSN_AFFINITY: '{{.SSN_AFFINITY | default "no"}}'
      _USE_HTTP2: '{{.USE_HTTP2 | default "no"}}'
      _AUTHENTICATE: '{{.AUTHENTICATE | default "yes"}}' 
      _HTTP_PORT: '{{.HTTP_PORT | default "8080"}}'
      _VPC_EGRESS: '{{.VPC_EGRESS | default "private-ranges-only"}}'
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - >-
        {{.RUN_CMD}} deploy
        {{.RUN_SERVICE}}
        --project={{.GCP_PROJECT}}
        --region={{.RUN_REGION}}
        --concurrency={{._CONCURRENCY}}
        --min-instances={{._MIN_INSTANCES}}
        --max-instances={{._MAX_INSTANCES}}
        --timeout={{._TIMEOUT}}
        --cpu={{._CPU}}
        --memory={{._MEMORY}}
        --execution-environment=gen{{._GENERATION}}
        --ingress={{._INGRESS}}
        --platform={{._PLATFORM}}
        --port={{._HTTP_PORT}}
        --{{if eq ._CPU_BOOST "no"}}no-{{end}}cpu-boost
        --{{if eq ._CPU_THROTTLE "no"}}no-{{end}}cpu-throttling
        --{{if eq ._SSN_AFFINITY "no"}}no-{{end}}session-affinity
        --{{if eq ._USE_HTTP2 "no"}}no-{{end}}use-http2
        --{{if eq ._AUTHENTICATE "yes"}}no-{{end}}allow-unauthenticated
        --{{if .VPC_CONNECTOR}}vpc-connector={{.VPC_CONNECTOR}}{{else}}clear-vpc-connector{{end}}
        {{if .VPC_EGRESS}}--vpc-egress={{._VPC_EGRESS}}{{end}}
        {{if .IMAGE_TAG}}--image={{.IMAGE_TAG}}{{end}}
        {{if .ENV_VARS}}--set-env-vars='{{.ENV_VARS}}'{{end}}
        {{if .SERVICE_ACCOUNT}}--service-account={{.SERVICE_ACCOUNT}}{{end}}
