version: '3'

vars:
  G_SECRETS_VERSIONS_CMD: 'gcloud secrets versions'

tasks:

  default:
    cmds:
      - cmd: echo '{{.G_SECRETS_VERSIONS_CMD}} ...'

  access_latest:
    requires:
      vars:
        - GCP_PROJECT
        - SECRET_NAME
    dir: '{{.USER_WORKING_DIR}}'
    vars:
      OUTPUT: '{{.OUTPUT | default "/dev/stdout"}}'
    cmds:
      - >-
        {{.G_SECRETS_VERSIONS_CMD}}
        access latest
        --secret={{.SECRET_NAME}}
        --project={{.GCP_PROJECT}}
        > {{.OUTPUT}}
