version: '3'

includes:
  gcloud_secrets_versions:
    taskfile: 'secrets_versions.yaml'
    aliases: [versions]

vars:
  G_SECRETS_CMD: 'gcloud secrets'

tasks:

  default:
    cmds:
      - cmd: echo '{{.G_SECRETS_CMD}} ...'

  create:
    requires:
      vars:
        - GCP_PROJECT
        - SECRET_NAME
        - SECRET_VALUE
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - >-
        printf '{{.SECRET_VALUE}}'
        | {{.G_SECRETS_CMD}}
        create {{.SECRET_NAME}}
        --data-file=-
        --replication-policy='automatic'
        --project={{.GCP_PROJECT}}

  create_with_file:
    requires:
      vars:
        - GCP_PROJECT
        - SECRET_NAME
        - SECRET_FILE
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - >-
        {{.G_SECRETS_CMD}}
        create {{.SECRET_NAME}}
        --data-file={{.SECRET_FILE}}
        --replication-policy='automatic'
        --project={{.GCP_PROJECT}}
