version: '3'

vars:
  GCLOUD_CMD: 'gcloud services'

tasks:

  default:
    cmds:
      - echo '{{.GCLOUD_CMD}} ...'

  enable:
    requires:
      vars: [SERVICES]
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - for: { var: SERVICES, split: ',' }
        task: enable_service
        vars:
          SERVICE: '{{.ITEM}}'

  enable_service:
    internal: true
    requires:
      vars: [SERVICE]
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - cmd: '{{.GCLOUD_CMD}} enable {{.SERVICE}}.googleapis.com --format=json'
