#!/usr/bin/env bash

gcloud auth login

set -x

source .environment

rm -rvf ${TMP_DIR}
rm -rvf ${BIN_DIR}

mkdir -p ${REPO_DIR}/{bin,tmp}

curl -L -o ${DIRENV_BIN} "${DIRENV_DL_URL}"
chmod +x ${DIRENV_BIN}

mkdir ${TASK_TMP_DIR}
curl -L -o ${TASK_DL_TGZ} "${TASK_DL_URL}"
tar -xf ${TASK_DL_TGZ} --directory ${TASK_TMP_DIR}
ln -s ${TASK_TMP_BIN} ${TASK_BIN}

mkdir ${DAGU_TMP_DIR}
mkdir -p ${DAGU_DL_DIR}
curl -L -o ${DAGU_DL_TGZ} "${DAGU_DL_URL}"
tar -xf ${DAGU_DL_TGZ} --directory ${DAGU_DL_DIR}
ln -s ${DAGU_DL_BIN} ${DAGU_BIN}
mkdir -p ${DAGU_LOG_DIR}
mkdir -p ${DAGU_DATA_DIR}
mkdir -p ${DAGU_WORK_DIR}

export PATH=${BIN_DIR}:${PATH}

exec env ${DAGU_CMD} --host=${DAGU_HOST} --port=${DAGU_PORT} --dags=${DAGU_DAGS} --config=${DAGU_BASE_CONFIG}
