#!/usr/bin/env bash

gcloud projects list --limit=5

set -x

source .environment

rm -rf ${TMP_DIR}
rm -rf ${BIN_DIR}

mkdir -p ${REPO_DIR}/{bin,tmp}

curl -L -o ${DIRENV_BIN} "${DIRENV_DL_URL}"
chmod +x ${DIRENV_BIN}

curl -L -o ${YQ_BIN} "${YQ_DL_URL}"
chmod +x ${YQ_BIN}

mkdir ${TASK_TMP_DIR}
curl -L -o ${TASK_DL_TGZ} "${TASK_DL_URL}"
tar -xf ${TASK_DL_TGZ} --directory ${TASK_TMP_DIR}
ln -s ${TASK_TMP_BIN} ${TASK_BIN}

mkdir ${DAGU_TMP_DIR}
mkdir -p ${DAGU_DL_DIR}
curl -L -o ${DAGU_DL_TGZ} "${DAGU_DL_URL}"
tar -xf ${DAGU_DL_TGZ} --directory ${DAGU_DL_DIR}
ln -s ${DAGU_DL_BIN} ${DAGU_BIN}
ln -s ${DAGU_DL_BIN} ${BIN_DIR}/dag
mkdir -p ${DAGU_LOG_DIR}
mkdir -p ${DAGU_DATA_DIR}
mkdir -p ${DAGU_WORK_DIR}

RUN_CMD="${BIN_DIR}/run"
echo -e "#!/bin/bash\necho "run: \${1}/\${2}[\${3}]"\nexec env ${BIN_DIR}/\${1} \${2} \"\${@:3}\"" > ${RUN_CMD}
chmod +x ${RUN_CMD}

export PATH=${BIN_DIR}:${PATH}

exec env ${DAGU_CMD} --host=${DAGU_HOST} --port=${DAGU_PORT} --dags=${DAGU_DAGS} --config=${DAGU_BASE_CONFIG}
