version: '3'

vars:
  _GCLOUD_CMD: '{{.GCLOUD_CMD}} services'

tasks:

  default:
    cmds:
      - echo '{{.GCLOUD_CMD}} ...'

  describe:
    requires:
      vars: [TASK_DIR, GCP_PROJECT, RUN_SERVICE, RUN_REGION]
    vars:
      _FORMAT: '{{.FORMAT | default "json"}}'
    dir: '{{.TASK_DIR}}'
    cmds:
      - cmd: '{{._GCLOUD_CMD}} describe {{.RUN_SERVICE}} --region={{.RUN_REGION}} --project={{.GCP_PROJECT}} --format={{._FORMAT}}'
