version: '3'

includes:
  gcloud_appengine:
    taskfile: "../gcloud/appengine.yaml"
  gcloud_identity:
    taskfile: "../gcloud/identity.yaml"

vars:
  OIDC_IDP_JSON: '{{.USER_WORKING_DIR}}/idp_provider.json'

tasks:

  produce_oidc_provider:
    internal: true
    requires:
      vars: [GCP_PROJECT, GAE_SERVICE, PROVIDER_NAME]
    dir: '{{.USER_WORKING_DIR}}'
    vars:
      GAE_VERSIONS_FILE: '{{.USER_WORKING_DIR}}/gae_versions.json'
      GAE_ENV_VARS_FILE: '{{.USER_WORKING_DIR}}/gae_env_vars.json'
      REQUIRED_VARS: |-
        OIDC_ISSUER
        OIDC_CLIENT_ID
        OIDC_CLIENT_SECRET
    cmds:
      - task: gcloud_appengine:app_versions:list
        vars:
          FORMAT: '''json(version.id)'''
          FILTER: '''traffic_split=1.0'''
          OUTPUT: '{{.GAE_VERSIONS_FILE}}'
      - task: gcloud_appengine:app_versions:describe
        vars:
          GAE_VERSION:
            sh: 'jq -rcM ''.[0].version.id'' {{.GAE_VERSIONS_FILE}}'
          FORMAT: '''json(envVariables)'''
          OUTPUT: '{{.GAE_ENV_VARS_FILE}}'
      - |
        {{range $i, $v := .REQUIRED_VARS | splitLines -}}
        {{$v}}=`jq -rcM '.envVariables.{{$v}}' {{.GAE_ENV_VARS_FILE}}`
        {{end}}
        cat << EOF | tee {{.OIDC_IDP_JSON}}
        {
          "name": "{{.PROVIDER_NAME}}",
          "clientId": "${OIDC_CLIENT_ID}",
          "issuer": "${OIDC_ISSUER}",
          "displayName": "{{.PROVIDER_NAME}}",
          "enabled": true,
          "clientSecret": "${OIDC_CLIENT_SECRET}",
          "responseType": {
            "idToken": false,
            "code": true
          }
        }
        EOF
        jq -rcM < {{.OIDC_IDP_JSON}} | sponge {{.OIDC_IDP_JSON}}
      - cat -n {{.OIDC_IDP_JSON}}

  create_oidc_provider:
    requires:
      vars: [GCP_PROJECT, GAE_SERVICE, PROVIDER_NAME]
    dir: '{{.USER_WORKING_DIR}}'
    deps:
      - task: produce_oidc_provider
    cmds:
      - task: gcloud_identity:providers:create_oidc
        vars:
          GCP_PROJECT: '{{.GCP_PROJECT}}'
          PROVIDER_NAME: '{{.PROVIDER_NAME}}'
          PROVIDER_JSON: '@{{.OIDC_IDP_JSON}}'
