version: '3'

includes:
  gcloud_run: 
    taskfile: "../gcloud/run.yaml"

tasks:

  deploy_run_revision:
    requires:
      vars: 
        - GCP_PROJECT
        - RUN_SERVICE
        - RUN_REGION
        - BUILD_DATA
    dir: '{{.USER_WORKING_DIR}}'
    vars:
      SSH_SERVER_IMAGE:
        sh: >-
          jq -crM '.images[0]' < {{.BUILD_DATA}} | tr -d '\n'
    cmds: 
      - task: gcloud_run:deploy_container_image
        vars:
          IMAGE_TAG: '{{.SSH_SERVER_IMAGE}}'
          HTTP_PORT: 8080
          CPU: 2
          MEMORY: 2Gi
          CONCURRENCY: 10
          GENERATION: 2
          MIN_INSTANCES: 1
          MAX_INTANCES: 1
          TIMEOUT: 3600
          CPU_BOOST: yes
          CPU_THROTTLE: no
          SSN_AFFINITY: yes
          USE_HTTP2: no

  describe_run_revision:
    requires:
      vars: [GCP_PROJECT, RUN_SERVICE, RUN_REGION]
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - task: gcloud_run:run_services:describe
        vars:
          FORMAT: flattened

