version: '3'

includes:
  git:
    taskfile: "../common/git.yaml"
  gcloud_config: 
    taskfile: "../gcloud/config.yaml"
  gcloud_services: 
    taskfile: "../gcloud/services.yaml"
  gcloud_builds: 
    taskfile: "../gcloud/builds.yaml"
  gcloud_run: 
    taskfile: "../gcloud/run.yaml"

tasks:

  clone_git_repo:
    requires:
      vars: [GIT_REPO_URL, GIT_REPO_DIR]
    dir: '{{.USER_WORKING_DIR}}'
    cmds: 
      - task: git:clone

  set_gcp_project:
    requires:
      vars: [GCP_PROJECT]
    dir: '{{.USER_WORKING_DIR}}'
    cmds: 
      - task: gcloud_config:set_project

  enable_services:
    requires:
      vars: [GCP_PROJECT, GCP_SERVICES]
    dir: '{{.USER_WORKING_DIR}}'
    cmds: 
      - task: gcloud_services:enable
        vars:
          SERVICES: '{{.GCP_SERVICES}}'

  create_container_image:
    requires:
      vars: [GCP_PROJECT, RUN_SERVICE]
    dir: '{{.USER_WORKING_DIR}}'
    cmds: 
      - task: gcloud_builds:submit_using_pack
        vars:
          IMAGE_TAG: 'gcr.io/{{.GCP_PROJECT}}/{{.RUN_SERVICE}}'

  deploy_run_revision:
    requires:
      vars: [GCP_PROJECT, RUN_SERVICE, RUN_REGION]
    dir: '{{.USER_WORKING_DIR}}'
    cmds: 
      - task: gcloud_run:deploy_container_image
        vars:
          IMAGE_TAG: 'gcr.io/{{.GCP_PROJECT}}/{{.RUN_SERVICE}}'

  describe_run_revision:
    requires:
      vars: [GCP_PROJECT, RUN_SERVICE, RUN_REGION]
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - task: gcloud_run:run_services:describe
        vars:
          FORMAT: flattened

