version: '3'

includes:
  gcloud_config: 
    taskfile: "../../gcloud_config.yaml"
    aliases: [cfg]
  gcloud_builds: 
    taskfile: "../../gcloud_builds.yaml"
    aliases: [builds]
  gcloud_run: 
    taskfile: "../../gcloud_run.yaml"
    aliases: [run]

tasks:

  prepare_work_dir:
    cmds:
      - rm -rf $DAG_WORK_DIR
      - mkdir -p $DAG_WORK_DIR

  clone_git_repo:
    requires:
      vars: [TASK_DIR, GIT_REPO_URL]
    dir: '{{.TASK_DIR}}'
    cmds: 
      - cmd: git clone --depth=1 '{{.GIT_REPO_URL}}'

  set_gcp_project:
    requires:
      vars: [TASK_DIR, GCP_PROJECT]
    dir: '{{.TASK_DIR}}'
    cmds: 
      - task: cfg:set_project

  create_container_image:
    requires:
      vars: [TASK_DIR, GCP_PROJECT, RUN_SERVICE]
    dir: '{{.TASK_DIR}}'
    cmds: 
      - task: builds:submit_to_gcr_using_pack
        vars:
          IMAGE_TAG: 'gcr.io/{{.GCP_PROJECT}}/{{.RUN_SERVICE}}'

  deploy_run_revision:
    requires:
      vars: [TASK_DIR, GCP_PROJECT, RUN_SERVICE, RUN_REGION]
    dir: '{{.TASK_DIR}}'
    cmds: 
      - task: run:deploy_container_image
        vars:
          IMAGE_TAG: 'gcr.io/{{.GCP_PROJECT}}/{{.RUN_SERVICE}}'

  describe_run_revision:
    requires:
      vars: [TASK_DIR, GCP_PROJECT, RUN_SERVICE, RUN_REGION]
    dir: '{{.TASK_DIR}}'
    cmds:
      - task: run:svc:describe
        vars:
          FORMAT: flattened

