version: '3'

tasks:
  prepare_work_dir:
    cmds:
      - rm -rf $DAG_WORK_DIR
      - mkdir -p $DAG_WORK_DIR

  clone_github_repo:
    dir: '{{.DAG_WORK_DIR}}'
    cmds: 
      - git clone --depth=1 $GIT_REPO
