version: '3'

includes:
  git:
    taskfile: "../common/git.yaml"
  gcloud_config: 
    taskfile: "../gcloud/config.yaml"
  gcloud_services: 
    taskfile: "../gcloud/services.yaml"
  gcloud_app: 
    taskfile: "../gcloud/appengine.yaml"

tasks:

  clone_git_repo:
    requires:
      vars: [GIT_REPO_URL, GIT_REPO_DIR]
    dir: '{{.USER_WORKING_DIR}}'
    cmds: 
      - task: git:clone

  set_gcp_project:
    requires:
      vars: [GCP_PROJECT]
    dir: '{{.USER_WORKING_DIR}}'
    cmds: 
      - task: gcloud_config:set_project

  enable_services:
    requires:
      vars: [GCP_PROJECT, GCP_SERVICES]
    dir: '{{.USER_WORKING_DIR}}'
    cmds: 
      - task: gcloud_services:enable
        vars:
          SERVICES: '{{.GCP_SERVICES}}'

  deploy_app:
    requires:
      vars: [GCP_PROJECT]
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - task: gcloud_app:deploy
        vars:
          GAE_SERVICE: '{{.GAE_SERVICE | default "default"}}'
          GAE_VERSION: '{{.GAE_VERSION | default "v1-0-0"}}'

  describe_service:
    requires:
      vars: [GCP_PROJECT, GAE_SERVICE]
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - task: gcloud_app:app_services:describe
        vars:
          FORMAT: flattened

